from cgi import test
from importlib.metadata import distribution
from numbers import Real
from django.test import TestCase
import datetime

from .models import RealTimeMeter, SmartMeter, ThirtyMinAvg
from .tasks import _calc_thirty_min_avg, _calc_weather_data


# Create your tests here.
class DataCollectionTestCase(TestCase):
    def setUp(self):
        SmartMeter.objects.create(
            ip_address="172.20.49.4",
            field_name="EC_SM1",
            distribution_board="Energy Centre",
            latitude=35.146506,
            longitude=33.415653,
            feeder_connection="TRS4",
            feeder="Incomer",
            serial_no="ME-1801C724-02",
            modbus_port=502,
            mac_address="6078089165",
            comments="This is a test",
            username="admin",
            password="0",
            secondary_id=1,
        )

        for i in range(10):
            RealTimeMeter.objects.create(
                smart_meter=SmartMeter.objects.get(field_name="EC_SM1"),
                timestamp=datetime.datetime.now(),
                active=i,
                reactive=i,
                apparent=i,
                power_factor=i,
                freq=i,
            )

        RealTimeMeter.objects.create(
            smart_meter=SmartMeter.objects.get(field_name="EC_SM1"),
            timestamp=datetime.datetime.now() - datetime.timedelta(minutes=130),
            active=10,
            reactive=10,
            apparent=10,
            power_factor=10,
            freq=10,
        )

    def test_calc_weather_data(self):
        test_dict = {
            "success": True,
            "error": None,
            "response": [
                {
                    "loc": {"lat": 35.146032, "long": 35.146032},
                    "place": {"name": "latakia", "state": "la", "country": "sy"},
                    "periods": [
                        {
                            "timestamp": 1718266500,
                            "dateTimeISO": "2024-06-13T11:15:00+03:00",
                            "tempC": 28.79,
                            "tempF": 83.82,
                            "feelslikeC": 32.93,
                            "feelslikeF": 91.28,
                            "dewpointC": 23.62,
                            "dewpointF": 74.52,
                            "humidity": 74,
                            "pressureMB": 1011,
                            "pressureIN": 29.85,
                            "windDir": "NNW",
                            "windDirDEG": 342,
                            "windSpeedKTS": 3.85,
                            "windSpeedKPH": 7.13,
                            "windSpeedMPH": 4.43,
                            "windSpeedMPS": 1.98,
                            "windGustKTS": 4.96,
                            "windGustKPH": 9.18,
                            "windGustMPH": 5.7,
                            "windGustMPS": 2.55,
                            "precipMM": 0,
                            "precipIN": 0,
                            "precipRateMM": 0,
                            "precipRateIN": 0,
                            "snowCM": 0,
                            "snowIN": 0,
                            "snowRateCM": 0,
                            "snowRateIN": 0,
                            "snowDepthCM": 0,
                            "snowDepthIN": 0,
                            "pop": None,
                            "visibilityKM": 16,
                            "visibilityMI": 9.942,
                            "sky": 24,
                            "cloudsCoded": "FW",
                            "weather": "Mostly Sunny",
                            "weatherCoded": "::FW",
                            "weatherPrimary": "Mostly Sunny",
                            "weatherPrimaryCoded": "::FW",
                            "icon": "fair.png",
                            "solradWM2": 910,
                            "uvi": 8,
                            "isDay": True,
                            "spressureMB": 1007.7,
                            "spressureIN": 29.76,
                            "altimeterMB": 1010.9,
                            "altimeterIN": 29.85,
                            "solrad": {
                                "azimuthDEG": 117.1906,
                                "zenithDEG": 21.9474,
                                "ghiWM2": 910.0273,
                                "dniWM2": 722.8489,
                                "dhiWM2": 239.5651,
                                "version": "v2",
                            },
                        },
                        {
                            "timestamp": 1718267100,
                            "dateTimeISO": "2024-06-13T11:25:00+03:00",
                            "tempC": 28.92,
                            "tempF": 84.06,
                            "feelslikeC": 33.15,
                            "feelslikeF": 91.67,
                            "dewpointC": 23.64,
                            "dewpointF": 74.55,
                            "humidity": 73,
                            "pressureMB": 1011,
                            "pressureIN": 29.85,
                            "windDir": "NNW",
                            "windDirDEG": 342,
                            "windSpeedKTS": 3.83,
                            "windSpeedKPH": 7.09,
                            "windSpeedMPH": 4.41,
                            "windSpeedMPS": 1.97,
                            "windGustKTS": 4.94,
                            "windGustKPH": 9.14,
                            "windGustMPH": 5.68,
                            "windGustMPS": 2.54,
                            "precipMM": 0,
                            "precipIN": 0,
                            "precipRateMM": 0,
                            "precipRateIN": 0,
                            "snowCM": 0,
                            "snowIN": 0,
                            "snowRateCM": 0,
                            "snowRateIN": 0,
                            "snowDepthCM": 0,
                            "snowDepthIN": 0,
                            "pop": None,
                            "visibilityKM": 16,
                            "visibilityMI": 9.942,
                            "sky": 23,
                            "cloudsCoded": "FW",
                            "weather": "Mostly Sunny",
                            "weatherCoded": "::FW",
                            "weatherPrimary": "Mostly Sunny",
                            "weatherPrimaryCoded": "::FW",
                            "icon": "fair.png",
                            "solradWM2": 922,
                            "uvi": 9,
                            "isDay": True,
                            "spressureMB": 1007.7,
                            "spressureIN": 29.76,
                            "altimeterMB": 1010.9,
                            "altimeterIN": 29.85,
                            "solrad": {
                                "azimuthDEG": 121.2199,
                                "zenithDEG": 20.1626,
                                "ghiWM2": 921.9527,
                                "dniWM2": 718.4091,
                                "dhiWM2": 247.5689,
                                "version": "v2",
                            },
                        },
                        {
                            "timestamp": 1718267700,
                            "dateTimeISO": "2024-06-13T11:35:00+03:00",
                            "tempC": 29.05,
                            "tempF": 84.29,
                            "feelslikeC": 33.36,
                            "feelslikeF": 92.04,
                            "dewpointC": 23.65,
                            "dewpointF": 74.57,
                            "humidity": 73,
                            "pressureMB": 1011,
                            "pressureIN": 29.85,
                            "windDir": "NNW",
                            "windDirDEG": 342,
                            "windSpeedKTS": 3.81,
                            "windSpeedKPH": 7.06,
                            "windSpeedMPH": 4.38,
                            "windSpeedMPS": 1.96,
                            "windGustKTS": 4.92,
                            "windGustKPH": 9.11,
                            "windGustMPH": 5.66,
                            "windGustMPS": 2.53,
                            "precipMM": 0,
                            "precipIN": 0,
                            "precipRateMM": 0,
                            "precipRateIN": 0,
                            "snowCM": 0,
                            "snowIN": 0,
                            "snowRateCM": 0,
                            "snowRateIN": 0,
                            "snowDepthCM": 0,
                            "snowDepthIN": 0,
                            "pop": None,
                            "visibilityKM": 16,
                            "visibilityMI": 9.942,
                            "sky": 23,
                            "cloudsCoded": "FW",
                            "weather": "Mostly Sunny",
                            "weatherCoded": "::FW",
                            "weatherPrimary": "Mostly Sunny",
                            "weatherPrimaryCoded": "::FW",
                            "icon": "fair.png",
                            "solradWM2": 932,
                            "uvi": 9,
                            "isDay": True,
                            "spressureMB": 1007.7,
                            "spressureIN": 29.76,
                            "altimeterMB": 1010.9,
                            "altimeterIN": 29.85,
                            "solrad": {
                                "azimuthDEG": 125.8827,
                                "zenithDEG": 18.4583,
                                "ghiWM2": 931.6234,
                                "dniWM2": 711.8607,
                                "dhiWM2": 256.3847,
                                "version": "v2",
                            },
                        },
                        {
                            "timestamp": 1718268300,
                            "dateTimeISO": "2024-06-13T11:45:00+03:00",
                            "tempC": 29.18,
                            "tempF": 84.52,
                            "feelslikeC": 33.56,
                            "feelslikeF": 92.41,
                            "dewpointC": 23.66,
                            "dewpointF": 74.59,
                            "humidity": 72,
                            "pressureMB": 1011,
                            "pressureIN": 29.85,
                            "windDir": "NNW",
                            "windDirDEG": 342,
                            "windSpeedKTS": 3.79,
                            "windSpeedKPH": 7.02,
                            "windSpeedMPH": 4.36,
                            "windSpeedMPS": 1.95,
                            "windGustKTS": 4.9,
                            "windGustKPH": 9.07,
                            "windGustMPH": 5.64,
                            "windGustMPS": 2.52,
                            "precipMM": 0,
                            "precipIN": 0,
                            "precipRateMM": 0,
                            "precipRateIN": 0,
                            "snowCM": 0,
                            "snowIN": 0,
                            "snowRateCM": 0,
                            "snowRateIN": 0,
                            "snowDepthCM": 0,
                            "snowDepthIN": 0,
                            "pop": None,
                            "visibilityKM": 16,
                            "visibilityMI": 9.942,
                            "sky": 22,
                            "cloudsCoded": "FW",
                            "weather": "Mostly Sunny",
                            "weatherCoded": "::FW",
                            "weatherPrimary": "Mostly Sunny",
                            "weatherPrimaryCoded": "::FW",
                            "icon": "fair.png",
                            "solradWM2": 933,
                            "uvi": 9,
                            "isDay": True,
                            "spressureMB": 1007.7,
                            "spressureIN": 29.76,
                            "altimeterMB": 1010.9,
                            "altimeterIN": 29.85,
                            "solrad": {
                                "azimuthDEG": 131.328,
                                "zenithDEG": 16.8597,
                                "ghiWM2": 933.1654,
                                "dniWM2": 684.974,
                                "dhiWM2": 277.6332,
                                "version": "v2",
                            },
                        },
                    ],
                    "profile": {
                        "tz": "Asia/Damascus",
                        "tzname": "+03",
                        "tzoffset": 10800,
                        "isDST": False,
                        "elevM": 29,
                        "elevFT": 95,
                    },
                }
            ],
        }
        weather_data = _calc_weather_data(test_dict)
        self.assertEqual(weather_data["temp_C"], 28.985)

    def test_calc_thirty_min_avg(self):
        _calc_thirty_min_avg()
        self.assertEqual(
            RealTimeMeter.objects.all().count(), 10
        )  # test deletion of old data
        self.assertEqual(
            ThirtyMinAvg.objects.all().count(), 1
        )  # test creation of 30 min avg
        self.assertEqual(ThirtyMinAvg.objects.get().active, 4.5)
