# Generated by Django 5.0.6 on 2024-07-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ess',
            old_name='dd',
            new_name='depth_of_discharge',
        ),
        migrations.RenameField(
            model_name='ess',
            old_name='max_power',
            new_name='max_charge',
        ),
        migrations.RenameField(
            model_name='ess',
            old_name='sd',
            new_name='self_discharge',
        ),
        migrations.RemoveField(
            model_name='ess',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='ess',
            name='rte',
        ),
        migrations.AddField(
            model_name='ess',
            name='charge_efficiency',
            field=models.FloatField(default=1, verbose_name='Charge Efficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='discharge_efficiency',
            field=models.FloatField(default=1, verbose_name='Discharge Efficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='max_discharge',
            field=models.FloatField(default=1, verbose_name='Max Discharge Power'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='pref_max_soc',
            field=models.FloatField(default=1, verbose_name='Preferred Max SOC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='pref_min_soc',
            field=models.FloatField(default=1, verbose_name='Preferred Min SOC'),
            preserve_default=False,
        ),
    ]
