# Generated by Django 5.0.6 on 2024-06-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('distribution_board', models.CharField(max_length=255, verbose_name='Distribution Board')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('feeder_connection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feeder Connection')),
                ('feeder', models.CharField(max_length=255, verbose_name='Feeder')),
                ('serial_no', models.CharField(max_length=255, verbose_name='Serial No.')),
                ('modbus_port', models.PositiveIntegerField(verbose_name='Modbus Port')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('installed', models.BooleanField(default=False, verbose_name='Installed?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('secondary_id', models.BooleanField(default=False, verbose_name='Secondary Id')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('active', models.FloatField(blank=True, null=True)),
                ('reactive', models.FloatField(blank=True, null=True)),
                ('apparent', models.FloatField(blank=True, null=True)),
                ('freq', models.FloatField(blank=True, null=True)),
                ('smart_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.smartmeter')),
            ],
        ),
        migrations.CreateModel(
            name='ThirtyMinAvg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('active', models.FloatField(blank=True, null=True)),
                ('reactive', models.FloatField(blank=True, null=True)),
                ('apparent', models.FloatField(blank=True, null=True)),
                ('freq', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('irradiance', models.FloatField(blank=True, null=True)),
                ('smart_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.smartmeter')),
            ],
        ),
    ]
