# Generated by Django 5.0.6 on 2024-06-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmeter',
            name='installed',
        ),
    ]
