# Generated by Django 5.0.6 on 2024-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_rename_irradiance_thirtyminavg_ghi_wm2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='timezone',
            field=models.CharField(default='Europe/Nicosia', max_length=255, verbose_name='Timezone'),
        ),
    ]
