# Generated by Django 5.0.6 on 2024-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_remove_smartmeter_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimemeter',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thirtyminavg',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
