# Generated by Django 5.0.6 on 2024-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_smartmeter_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
